<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>HFA.Messaging</PackageId>
    <Version>1.0.1</Version>
    <Authors>HFA Team</Authors>
    <Company>HFA</Company>
  </PropertyGroup>
</Project>
